# Use https://github.com/secretlint/secretlint/pkgs/container/secretlint
---
name: secretlint
on:
  push:
jobs:
  secretlint:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/secretlint/secretlint:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: secretlint
        run: |
          secretlint "**/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
